name: novamart_smart_cart
description: NovaMart Smart Cart — Customer App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # QR / Barcode scanning
  mobile_scanner: ^5.2.3
  
  # HTTP
  http: ^1.2.1
  
  # Local storage
  shared_preferences: ^2.2.3
  
  # UI
  google_fonts: ^6.2.1
  
  # QR code generation (for display)
  qr_flutter: ^4.1.0
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Animations
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
